---
title: "Care seeking for diarrheal illnes: data quality checks"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r package install, message = FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  countrycode, here, lubridate, tidyverse, ggplot2,
  sf, raster, RColorBrewer, cowplot, kableExtra, flextable
)

# custom functions
source(here::here('code', 'utils.R'))
```

```{r import and rename variables}
data_extraction <- here::here("data", "extracted_data", "data_extractions.csv")
data <- read.csv(data_extraction)

#Study Design
data_recode <- data %>% rename(study_id = Study.ID,
              study_title = Title,
              citation = Citation,
              study_type = Study.Type,
              sampling_method = Sampling.Method,
              study_pop = Study.Population,
              study_pop_cat = Study.population.category,
              case_definition = Case.Definition,
              case_definition_cat = Case.definition.category,
              sampling_start = Date.Start,
              sampling_end = Date.End,
              study_context = Study.Context,
              outbreak = Outbreak.Description,
              notes = Notes,
              # Location Information
              entry_id = Entry.ID,
              entry_desc = Entry.Description,
              country_iso3 = Country.ISO3.Code,
              admin0 = GADM.Admin.0,
              admin1 = GADM.Admin.1..when.available,
              admin2 = GADM.Admin.2..when.available,
              admin3 = GADM.Admin.3..when.available,
              place_name = Precise.Place.Name,
              location_desc = Urban.or.Rural,
              location_details = Location.Description,
              #Care Seeking Data
              care_questions = Care.Seeking.Questions,
              care_seeking_timing = Timing.of.care.seeking,
              self_or_child = Regarding.self.or.child,
              recall_time = Recall.time..in.days.,
              care_location = Facility.or.location.sought.as.written.in.transcript,
              location_type = Type.of.care.facility.sought..standardized.,
              n_would_survey = N.surveyed.if.they.WOULD.seek.care,
              n_would = N.who.said.they.WOULD.seek.care,
              n_did_survey = N.surveyed.if.they.DID.seek.care,
              n_did = N.who.actually.DID.seek.care,
              csd_notes = Additional.Information,
              age_l = Age.lower..of.individual.with.diarrhea.in.years.,
              age_r = Age.Upper..of.individual.with.diarrhea.in.years.,
              prop_under5 = Proportion.of.individuals.with.diarrhea..5.years.old,
              sex = Sex..of.individual.with.diarrhea.,
              diar_severe = Diarrhea.severity,
              diar_symp = Diarrhea.symptoms,
              nutrition = Nutrition.Status,
              entries_overlap = Overlapping.Study,
              num_convert = Percents.converted.to.numbers,
              mult_choice = Multiple.Choices,
              extractor = Extractor.Initials,
              primary_dataset = Primary.dataset,
              strat_time = Stratified.time,
              strat_geo = Stratified.geographic.location,
              strat_location = Stratified.urban.rural,
              strat_age = Stratified.age,
              strat_sex = Stratified.sex,
              strat_severity = Stratified.severity
)

# Filter to primary dataset
data_recode <- data_recode %>%
  filter(primary_dataset == 1)

# some cleaning
data_recode <- data_recode %>%
  # simplify/clarify location description
  mutate(location_desc = ifelse(location_desc == 'IDP Camp (Internally Displaced Person) or Refugee Camp',
                                'IDP or Refugee Camp', 
                                ifelse(location_desc == 'Both', 'Urban and Rural', location_desc))) %>%
  # add start and end year
  mutate(sampling_start = as.Date(sampling_start, format = "%m/%d/%Y"),
         sampling_end = as.Date(sampling_end, format = "%m/%d/%Y"),
         TL = year(sampling_start),
         TR = year(sampling_end))
```

## Data Quality Checks

### Location information

```{r Quality Check, message = TRUE}
# quality check to make sure the ISO code is spelled correctly
data_recode$country_name <- countrycode(data_recode$country_iso3, "iso3c", "country.name")

wrong_iso <- data_recode %>%
  filter(is.na(country_name))

if (nrow(wrong_iso) > 0) {
  message('The following study_ids have incorrect ISO3 codes. They will be included for now but should be corrected:\n',
        paste0(unique(wrong_iso$study_id), sep = '\n'))
}
```

### Impossible values

```{r, message = TRUE}
# number surveyed larger than number surveyed
wrong_n <- data_recode %>%
  filter(n_did > n_did_survey)

if (nrow(wrong_n) > 0) {
  message('The following study_ids have the number surveyed smaller than the number that sought care. These will be excluded until fixed:\n',
        paste0(unique(wrong_n$study_id), sep = '\n'))

  # remove from data set until fixed
  data_recode <- data_recode %>%
    filter(n_did <= n_did_survey)
}

# start date is before end date
wrong_date <- data_recode %>%
  filter(sampling_start > sampling_end)

if (nrow(wrong_date) > 0) {
  message('The following study_ids have a sampling end date before a sampling start date. These will be excluded until fixed:\n',
        paste0(unique(wrong_date$study_id), sep = '\n'))

  # remove from data set until fixed
  data_recode <- data_recode %>%
    filter(n_did <= n_did_survey)
}
```

### Entry IDs

```{r, message = TRUE}
# entry_ids that have more than one N
wrong_eid <- data_recode %>%
  dplyr::select(c('entry_id', 'n_did_survey')) %>%
  unique() %>%
  group_by(entry_id) %>%
  reframe(n_check = sum(n_did_survey),
          n_did_survey = n_did_survey) %>%
  filter(n_did_survey != n_check)

wrong_eids <- unique(wrong_eid$entry_id)

if (length(wrong_eids) > 0) {
  message('The following entry_ids have more than one sample size listed and should be checked (they may need to be separated into multiple entry_ids). These will be excluded until fixed:\n',
        paste0(wrong_eids, sep = '\n'))

  # remove from data set until fixed
  data_recode <- data_recode %>%
    filter(!entry_id %in% wrong_eids)
}
```
